name: 'Visual Regresu=sion Tests'

on:
    pull_request:

jobs:
    storybook-deployment:
        runs-on: ubuntu-latest
        if: github.repository == 'PostHog/posthog'
        steps:
            - name: Check out PostHog/posthog repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: How can this work?
              run: yarn && node bin/visual-regression.js
            - name: Archive screenshots
              uses: actions/upload-artifact@v3
              with:
                  name: screenshots
                  path: screenshot*.png
